#!/bin/bash

DST="gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2" 

mkdir -p cache/

wget -O cache/$DST "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2?revision=05382cca-1721-44e1-ae19-1e7c3dc96118&rev=05382cca172144e1ae191e7c3dc96118&hash=3ACFE672E449EBA7A21773EE284A88BC7DFA5044"

ls -lh cache/$DST
md5sum cache/$DST
